### ISSUE TITLE
Using the HyperCubic struct to define models

### ISSUE THREAD

**Issue by LinjianMa** [ITensor/ITensorNetworkAD.jl#9]
Struct at: https://github.com/ITensor/ITensorNetworkAD.jl/blob/c178a13c63f95f8bc51e322f16eb6ab217b7217b/src/ITensorNetworks/tensor_networks.jl#L33-L40

The square_lattice in ITensors.jl is more geared towards a 1-dimensional "snake" pattern through a 2-dimensional lattice. The Square lattice type is more directly suited for 2 dimensions (for example, there are iterators over bonds/edges which are of the form ((2, 2), (2, 3)), so actual 2-dimensional coordinates for the sites). 

The localham_term function would need to be adapted to those new types of bonds.

**Comment by mtfishman** [comment]
Cross reference: https://github.com/ITensor/ITensorNetworkAD.jl/pull/8#discussion_r670459399_

**Comment by LinjianMa** [comment]
Fixed by #30
